kind: pipeline
type: kubernetes
name: default

steps:
- name: docker
  image: harbor.ntppool.org/ntppool/drone-kaniko:main
  pull: always
  settings:
    dockerfile: Dockerfile
    repo: library/prometheus-dnssec-exporter
    registry: harbor.ntppool.org
    auto_tag: true
    tags: SHA7,${DRONE_SOURCE_BRANCH}
    cache: true
    username:
      from_secret: harbor_library_username
    password:
      from_secret: harbor_library_password
